// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFollow = "follow"

// Follow mapped from table <follow>
type Follow struct {
	ID      int32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID  int32 `gorm:"column:user_id" json:"user_id"`
	FunID   int32 `gorm:"column:fun_id;not null" json:"fun_id"`
	Removed int32 `gorm:"column:removed;not null" json:"removed"`
	Deleted int32 `gorm:"column:deleted;not null" json:"deleted"`
}

// TableName Follow's table name
func (*Follow) TableName() string {
	return TableNameFollow
}
