// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Username   string    `gorm:"column:username;not null" json:"username"`
	Password   string    `gorm:"column:password;not null" json:"password"`
	LoginTime  time.Time `gorm:"column:login_time" json:"login_time"`
	Enable     int32     `gorm:"column:enable;default:1" json:"enable"`
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP" json:"create_time"`
	Deleted    int32     `gorm:"column:deleted" json:"deleted"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
